/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SistemaVacina.telas;

import br.com.SistemaVacina.controller.FormLoginController;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author samue
 */

public class TelaLogin extends javax.swing.JFrame {

    static void addActionListener(ActionListener actionListener) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private final FormLoginController controller;
    private Object JBarraNome;
    private Object JBarraSenha;
  
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        controller = new FormLoginController(this);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JbntSAIR = new javax.swing.JButton();
        jbntCADASTRAR = new javax.swing.JButton();
        JbntENTRAR = new javax.swing.JButton();
        JBETA = new javax.swing.JLabel();
        barrasenha = new javax.swing.JPasswordField();
        Jsenha = new javax.swing.JLabel();
        barranome = new javax.swing.JTextField();
        Jnome = new javax.swing.JLabel();
        JlogoLogin = new javax.swing.JLabel();
        TelaDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Vacina - Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbntSAIR.setText("SAIR");
        JbntSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbntSAIRActionPerformed(evt);
            }
        });
        getContentPane().add(JbntSAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jbntCADASTRAR.setText("CADASTRAR");
        jbntCADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntCADASTRARActionPerformed(evt);
            }
        });
        getContentPane().add(jbntCADASTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 260, 40));

        JbntENTRAR.setText("ENTRAR");
        JbntENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbntENTRARActionPerformed(evt);
            }
        });
        getContentPane().add(JbntENTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 260, 40));

        JBETA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBETA.setForeground(new java.awt.Color(255, 255, 255));
        JBETA.setText("BETA 0.0.0.1");
        getContentPane().add(JBETA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));
        getContentPane().add(barrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 290, 30));

        Jsenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jsenha.setForeground(new java.awt.Color(255, 255, 255));
        Jsenha.setText("SENHA:");
        getContentPane().add(Jsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        barranome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barranomeActionPerformed(evt);
            }
        });
        getContentPane().add(barranome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 290, 30));

        Jnome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jnome.setForeground(new java.awt.Color(255, 255, 255));
        Jnome.setText("NOME:");
        getContentPane().add(Jnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        JlogoLogin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JlogoLogin.setForeground(new java.awt.Color(255, 255, 255));
        JlogoLogin.setText("LOGIN");
        getContentPane().add(JlogoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        TelaDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SistemaVacina/icones/foto_inicial_01.jpg"))); // NOI18N
        getContentPane().add(TelaDeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbntCADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntCADASTRARActionPerformed
        TelaCadastro telaCadastro = new TelaCadastro();
    telaCadastro.setVisible(true);
    setVisible(false);
    }//GEN-LAST:event_jbntCADASTRARActionPerformed

    private void JbntENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbntENTRARActionPerformed
        try {
            controller.autenticar();
        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_JbntENTRARActionPerformed

    private void JbntSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbntSAIRActionPerformed
       // TODO: Adicione aqui o código personalizado antes de fechar a tela
         this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_JbntSAIRActionPerformed

    private void barranomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barranomeActionPerformed
        
    }//GEN-LAST:event_barranomeActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
                
            
            
        });
    }

    public JTextField getBarranome() {
        return barranome;
    }

    public void setBarranome(JTextField barranome) {
        this.barranome = barranome;
    }

    public JPasswordField getBarrasenha() {
        return barrasenha;
    }

    public void setBarrasenha(JPasswordField barrasenha) {
        this.barrasenha = barrasenha;
    }

  

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBETA;
    private javax.swing.JButton JbntENTRAR;
    private javax.swing.JButton JbntSAIR;
    private javax.swing.JLabel JlogoLogin;
    private javax.swing.JLabel Jnome;
    private javax.swing.JLabel Jsenha;
    private javax.swing.JLabel TelaDeFundo;
    private javax.swing.JTextField barranome;
    private javax.swing.JPasswordField barrasenha;
    private javax.swing.JButton jbntCADASTRAR;
    // End of variables declaration//GEN-END:variables
    {
}
}















