/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SistemaVacina.telas;

import br.com.SistemaVacina.Model.Usuario;
import br.com.SistemaVacina.controller.FormCadastroController;
import br.com.SistemaVacina.dal.ModuloConexao;
import br.com.SistemaVacina.dal.UsuarioDal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author samue
 */
public class TelaCadastro extends javax.swing.JFrame {
    private final FormCadastroController controller;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        controller = new FormCadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldcpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldtelefone = new javax.swing.JTextField();
        jTextFieldnome = new javax.swing.JTextField();
        jbntCONFIRMAR = new javax.swing.JButton();
        jbntVOLTAR = new javax.swing.JButton();
        Jemail = new javax.swing.JLabel();
        Jid = new javax.swing.JLabel();
        JTelefone = new javax.swing.JLabel();
        jSenha = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();
        jLogoRegistro = new javax.swing.JLabel();
        TelaDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Vacina - Cadastro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 280, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BETA 0.0.0.1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, -1, 20));
        getContentPane().add(jPasswordFieldsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 280, -1));
        getContentPane().add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 280, -1));
        getContentPane().add(jTextFieldtelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 280, -1));
        getContentPane().add(jTextFieldnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 280, -1));

        jbntCONFIRMAR.setText("CONFIRMAR");
        jbntCONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntCONFIRMARActionPerformed(evt);
            }
        });
        getContentPane().add(jbntCONFIRMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 220, 50));

        jbntVOLTAR.setText("VOLTAR");
        jbntVOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntVOLTARActionPerformed(evt);
            }
        });
        getContentPane().add(jbntVOLTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        Jemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jemail.setForeground(new java.awt.Color(255, 255, 255));
        Jemail.setText("EMAIL:");
        getContentPane().add(Jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        Jid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jid.setForeground(new java.awt.Color(255, 255, 255));
        Jid.setText("ID");
        getContentPane().add(Jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 70, 30));

        JTelefone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTelefone.setForeground(new java.awt.Color(255, 255, 255));
        JTelefone.setText("TELEFONE:");
        getContentPane().add(JTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, -1));

        jSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSenha.setForeground(new java.awt.Color(255, 255, 255));
        jSenha.setText("SENHA:");
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jNome.setForeground(new java.awt.Color(255, 255, 255));
        jNome.setText("NOME:");
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLogoRegistro.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLogoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jLogoRegistro.setText("CADASTRO");
        getContentPane().add(jLogoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        TelaDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SistemaVacina/icones/foto_inicial_01.jpg"))); // NOI18N
        getContentPane().add(TelaDeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbntCONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntCONFIRMARActionPerformed
          controller.salvaUsuario();
                
    }//GEN-LAST:event_jbntCONFIRMARActionPerformed

    private void jbntVOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntVOLTARActionPerformed
         TelaLogin telalogin = new TelaLogin();
    telalogin.setVisible(true);
    setVisible(false); // Oculta a TelaPrincipal

    }//GEN-LAST:event_jbntVOLTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    public JPasswordField getjPasswordFieldsenha() {
        return jPasswordFieldsenha;
    }

    public void setjPasswordFieldsenha(JPasswordField jPasswordFieldsenha) {
        this.jPasswordFieldsenha = jPasswordFieldsenha;
    }

    public JTextField getjTextFieldcpf() {
        return jTextFieldcpf;
    }

    public void setjTextFieldcpf(JTextField jTextFieldcpf) {
        this.jTextFieldcpf = jTextFieldcpf;
    }

    public JTextField getjTextFieldemail() {
        return jTextFieldemail;
    }

    public void setjTextFieldemail(JTextField jTextFieldemail) {
        this.jTextFieldemail = jTextFieldemail;
    }

    public JTextField getjTextFieldnome() {
        return jTextFieldnome;
    }

    public void setjTextFieldnome(JTextField jTextFieldnome) {
        this.jTextFieldnome = jTextFieldnome;
    }

    public JTextField getjTextFieldtelefone() {
        return jTextFieldtelefone;
    }

    public void setjTextFieldtelefone(JTextField jTextFieldtelefone) {
        this.jTextFieldtelefone = jTextFieldtelefone;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTelefone;
    private javax.swing.JLabel Jemail;
    private javax.swing.JLabel Jid;
    private javax.swing.JLabel TelaDeFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLogoRegistro;
    private javax.swing.JLabel jNome;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JLabel jSenha;
    private javax.swing.JTextField jTextFieldcpf;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldtelefone;
    private javax.swing.JButton jbntCONFIRMAR;
    private javax.swing.JButton jbntVOLTAR;
    // End of variables declaration//GEN-END:variables
}
