/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.SistemaVacina.telas;

/**
 *
 * @author samue
 */
public class TelaInfo extends javax.swing.JFrame {

    /**
     * Creates new form TelaInfo
     */
    public TelaInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JNOMEDOSCRIADORES = new javax.swing.JLabel();
        JESTROFE2 = new javax.swing.JLabel();
        JESTROFE1 = new javax.swing.JLabel();
        JNameLayout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INFO - Sistema De Vacina");
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E FACILITAR ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("--------");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 260, 70));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SAMUEL....");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 290, 70));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GERALDO....");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 290, 70));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GLEDISTRON .....");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 320, 70));

        JNOMEDOSCRIADORES.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JNOMEDOSCRIADORES.setForeground(new java.awt.Color(255, 255, 255));
        JNOMEDOSCRIADORES.setText("CRIADORES");
        getContentPane().add(JNOMEDOSCRIADORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 330, 80));

        JESTROFE2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JESTROFE2.setForeground(new java.awt.Color(255, 255, 255));
        JESTROFE2.setText("A APLICAÇÃO, E AJUDAR AS PESSOAS DURANTE AS APLICAÇÕES.");
        getContentPane().add(JESTROFE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 640, 70));

        JESTROFE1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JESTROFE1.setForeground(new java.awt.Color(255, 255, 255));
        JESTROFE1.setText("SISTEMA DE VACINA FEITO COM A FINALIDADE DE AUXILIAR ");
        getContentPane().add(JESTROFE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 770, 70));

        JNameLayout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JNameLayout.setForeground(new java.awt.Color(255, 255, 255));
        JNameLayout.setText("SISTEMA DE VACINA !");
        getContentPane().add(JNameLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 380, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SistemaVacina/icones/FOTOinfo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SistemaVacina/icones/LOGOINFO.png"))); // NOI18N
        jMenu1.setText("OPÇÕES");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/SistemaVacina/icones/LOGORETORNAR.png"))); // NOI18N
        jMenuItem1.setText("VOLTAR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       TelaUSUARIO1 telaVOLTAR = new TelaUSUARIO1 ();
    telaVOLTAR.setVisible(true);
    setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JESTROFE1;
    private javax.swing.JLabel JESTROFE2;
    private javax.swing.JLabel JNOMEDOSCRIADORES;
    private javax.swing.JLabel JNameLayout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
